[program:update-agent-sock]
command=/usr/local/bin/update-agent-sock
autostart=true
autorestart=true
# TODO writing a non-condor log to the condor ce location is not ideal but is useful for debugging
stdout_logfile=/var/log/condor-ce/update-agent-sock.log
stdout_logfile_maxbytes=0
redirect_stderr=true
