#!/bin/sh
condor_ce_q -print-format - "$@" <<'__END__'
SELECT
    (RoutedJob ?: "-")                          AS "R"   WIDTH 1
    ID                                          AS "JOB ID"   PRINTAS JOB_ID WIDTH 8
    Owner                                       AS "OWNER"   PRINTAS OWNER WIDTH -8
    QDate                                       AS " SUBMITTED"   PRINTAS QDATE WIDTH -12
    JobStatus                                   AS "STATUS"   PRINTAS JOB_STATUS
    EnteredCurrentStatus                        AS " SINCE"   PRINTAS QDATE WIDTH -12
    (OSG_PROJECT_NAME ?: (ProjectName ?: "-"))  AS "[OSG] PROJECT NAME"
    (BatchProject ?: "-")                       AS "BATCH PROJECT"
GROUP BY
    Owner
__END__

