#!/bin/bash
set -e
if [[ $(id -u) == 0 ]]; then
    user=${1?You must specify a user if you are root}
    shift
else
    user=$(id -un)
fi
global_ssh_config=/etc/ssh/ssh_config
login_host=$(awk "/^Match user \"$user\"/ {print \$5; exit}" "$global_ssh_config" | tr -d '""')
exec ssh -l "$user" -F "$global_ssh_config" "$login_host" "$@"
